export const SKILLS = [
  "Human Factor Principles",
  "W3C AC",
  "Mobile Design",
  "Atomic Design",
  "UX Research",
  "Agile methodologies",
  "User Acceptance Testing",
  "Design Sprint",
  "Pruebas de usabilidad",
  "Desing systems",
  "System grid",
  "Prototyping",
  "Documentacion",
  "Figma avanzado",
  "UI Guidelines",
  "Análisis cuantitativo y cualitativo",
  "Wireframes",
];
